cc_library(
  name = 'CppUnit',
  warning = 'no',
  export_incs = './include',
  srcs = [
    'src/CppUnitException.cpp',
    'src/TestCase.cpp',
    'src/TestDecorator.cpp',
    'src/TestFailure.cpp',
    'src/TestResult.cpp',
    'src/TestRunner.cpp',
    'src/TestSuite.cpp',
    'src/TextTestResult.cpp'
  ]
)
